### ISSUE TITLE
Import shapefile/FilterBound

### ISSUE THREAD

**Issue by GReimche** [giswqs/qgis-earthengine-examples#10]
Hi Dr. Wu,

I'm wondering about if it's possible to use a shapefile polygon loaded in Qgis in order to FilterBound a imageCollection?

Thank you
Geovane

**Comment by giswqs** [comment]
As far as I know, this is not possible. Earth Engine objects are server-side objects. Shapefiles on your local computer are client-side objects. You will have to upload shapefiles to GEE assets to become server-side objects. 

There is a workaround. You can use the coordinates of the polygon (or minimum bounding box) to create an ee.FeatureCollection. Then you can pass this into FilterBounds().

**Comment by giswqs** [comment]
@GReimche Check the links below:

- [Using ipyleaflet drawing tools to interact with Earth Engine data](https://github.com/giswqs/geemap/blob/master/examples/notebooks/ipyleaflet_draw_control.ipynb)
- [Video demo](https://i.imgur.com/SzauIsZ.gifv)
