### ISSUE TITLE
How to convert GEE JavaScript to Python?

### ISSUE THREAD

**Issue by aixiaodetianshi** [giswqs/qgis-earthengine-examples#7]
I have many JavaScript codes in gee, now, I work in Qgis using Python, I have convert_js_to_python.py code, But I do not know how to convert js to python, could you give to one example to help me? many thanks!

**Comment by csaybar** [comment]
You might use the [cover_js_to_python](https://github.com/giswqs/qgis-earthengine-examples/blob/master/convert_js_to_python.py)  module to help you in the translation. However, additional changes could also be necessary, it's depending on code complexity. A reproducible example [here](https://colab.research.google.com/drive/1IBXTWfC4FCBfNEsAvKg1scOY8zgDfJxS)

```
#script
!wget https://raw.githubusercontent.com/giswqs/qgis-earthengine-examples/master/convert_js_to_python.py
#js example
!wget https://raw.githubusercontent.com/renelikestacos/Google-Earth-Engine-JavaScript-Examples/master/010-modis_zonal_statistics_calculation.js
```

```python
from convert_js_to_python import js_to_python
in_file_path = '/content/010-modis_zonal_statistics_calculation.js'
with open(in_file_path, 'r') as f:
  for line in f:
    print(line)
```

```python
js_to_python('/content/010-modis_zonal_statistics_calculation.js')
with open(in_file_path, 'r') as f:
  for line in f:
    print(line)
```

**Comment by giswqs** [comment]
I have improved [convert_js_to_python.py](https://github.com/giswqs/qgis-earthengine-examples/blob/master/convert_js_to_python.py). See the example below. Simply change `in_file_path` to your JavaScript file path or `in_dir` to your JavaScript folder. 

As @csaybar mentioned, the conversion is not always perfect. Depending on the complexity of your scripts, some manual changes might be needed. 

```
if __name__ == '__main__':

    ## Convert one JavaScript file to Python
    root_dir = os.path.dirname(os.path.abspath(__file__))
    in_file_path = os.path.join(root_dir, "JavaScripts/NormalizedDifference.js")  # change this path to your JavaScript file
    out_file_path = os.path.splitext(in_file_path)[0] + ".py"
    js_to_python(in_file_path, out_file_path)
    print("Saved python script: {}".format(out_file_path))

    ## Convert all JavaScript files in a folder to Python
    in_dir = os.path.join(root_dir, "JavaScripts")   # change this path to your JavaScript folder
    for in_file_path in Path(in_dir).rglob('*.js'):
        out_file_path = os.path.splitext(in_file_path)[0] + ".py"
        js_to_python(in_file_path, out_file_path)
    print("Saved python script folder: {}".format(in_dir))
```

**Comment by Lecaethomas** [comment]
Hi, 
I'm really interested too, I have a lot of JS script, but I don't get how you make your script work. Could you give explanation about the context and method? By advance thanks,
Thomas

**Comment by giswqs** [comment]
@Lecaethomas Here are the steps:

1. Clone the repo (`git clone https://github.com/giswqs/qgis-earthengine-examples.git`)
2. Copy whatever GEE JavaScripts you want to convert into the [JavaScripts](https://github.com/giswqs/qgis-earthengine-examples/tree/master/JavaScripts) folder
3. Run [convert_js_to_python.py](https://github.com/giswqs/qgis-earthengine-examples/blob/master/convert_js_to_python.py)
4. Check the converted Python scripts under the [JavaScripts](https://github.com/giswqs/qgis-earthengine-examples/tree/master/JavaScripts) folder
5. Depending on the complexity of your JavaScripts, additional manual changes might be needed.

**Comment by giswqs** [comment]
@csaybar @aixiaodetianshi @Lecaethomas I have improved the conversion script significantly. Check [here](https://github.com/giswqs/earthengine-py-notebooks#3-how-to-automatically-convert-earth-engine-javascript-to-python-script).
