### ISSUE TITLE
How to export gee table using qgis+python?

### ISSUE THREAD

**Issue by aixiaodetianshi** [giswqs/qgis-earthengine-examples#8]
ls_collection = dates_modis.map(reduceLandsatNDVI)
dates_landsat = dates_modis.map(extract_landsat_date)
dates_landsat = dates_landsat.toList(20)
print(dates_landsat.get(0))
# mytask = ee.batch.Export.table.toDrive(collection=dates_landsat, folder='Qinghai_Lake_Bound', description=csv_title, fileFormat='CSV')
# ee.batch.data.startProcessing(mytask.id, mytask.config)
 There are errors, could you help me? Many thanks!

**Comment by giswqs** [comment]
See the example below.

https://github.com/giswqs/earthengine-py-notebooks/blob/master/AssetManagement/export_ee_data.ipynb

```
import ee

fc = ee.FeatureCollection('TIGER/2018/States') \
    .filter(ee.Filter.eq('STUSPS', 'TN'))

desc = 'tableToDriveExample'

# Set configration parameters for output vector
task_config = {
    'folder': 'gee-data', # output Google Drive folder
    'fileFormat': 'CSV',  
    'selectors': ['ALAND', 'NAME', 'STUSPS'] # a list of properties/attributes to be exported
    }

print('Exporting {}'.format(desc))
task = ee.batch.Export.table.toDrive(fc, desc, **task_config)
task.start()
```
